server:
  port: 8080

spring:
  application:
    name: gateway

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_HOST}
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_NAME}